//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PublishingHouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookExemplar
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public int Year { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Store Store { get; set; }
        public virtual Series Series { get; set; }
    }
}
